# Caso 1

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

In [3]:
#Importar base de datos
df = pd.read_csv('kl.csv', encoding='ISO-8859-1')

In [4]:
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31.0,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94.0,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226.5M
1,1,20801,Cristiano Ronaldo,33.0,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94.0,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127.1M
2,2,190871,Neymar Jr,26.0,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92.0,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228.1M
3,3,193080,De Gea,27.0,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91.0,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,138.6M
4,4,192985,K. De Bruyne,27.0,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91.0,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196.4M

In [5]:
df.info

<bound method DataFrame.info of        Unnamed: 0      ID                Name   Age  \
0               0  158023            L. Messi  31.0
1               1   20801   Cristiano Ronaldo  33.0
2               2  190871           Neymar Jr  26.0
3               3  193080              De Gea  27.0
4               4  192985        K. De Bruyne  27.0
...           ...     ...                 ...   ...
18202       18202  238813        J. Lundstram  19.0
18203       18203  243165  N. Christoffersson  19.0
18204       18204  241638           B. Worman  16.0
18205       18205  246268      D. Walker-Rice  17.0
18206       18206  246269           G. Nugent  16.0

                                                Photo Nationality  \
0      https://cdn.sofifa.org/players/4/19/158023.png   Argentina
1       https://cdn.sofifa.org/players/4/19/20801.png    Portugal
2      https://cdn.sofifa.org/players/4/19/190871.png      Brazil
3      https://cdn.sofifa.org/players/4/19/193080.png       Spain
4      https://cdn.sofifa.org/players/4/19/192985.png     Belgium
...                                               ...         ...
18202  https://cdn.sofifa.org/players/4/19/238813.png     England
18203  https://cdn.sofifa.org/players/4/19/243165.png      Sweden
18204  https://cdn.sofifa.org/players/4/19/241638.png     England
18205  https://cdn.sofifa.org/players/4/19/246268.png     England
18206  https://cdn.sofifa.org/players/4/19/246269.png     England

                                      Flag  Overall  Potential  \
0      https://cdn.sofifa.org/flags/52.png     94.0         94
1      https://cdn.sofifa.org/flags/38.png     94.0         94
2      https://cdn.sofifa.org/flags/54.png     92.0         93
3      https://cdn.sofifa.org/flags/45.png     91.0         93
4       https://cdn.sofifa.org/flags/7.png     91.0         92
...                                    ...      ...        ...
18202  https://cdn.sofifa.org/flags/14.png     47.0         65
18203  https://cdn.sofifa.org/flags/46.png     47.0         63
18204  https://cdn.sofifa.org/flags/14.png     47.0         67
18205  https://cdn.sofifa.org/flags/14.png     47.0         66
18206  https://cdn.sofifa.org/flags/14.png     46.0         66

                      Club  ... Composure Marking StandingTackle  \
0             FC Barcelona  ...      96.0    33.0           28.0
1                 Juventus  ...      95.0    28.0           31.0
2      Paris Saint-Germain  ...      94.0    27.0           24.0
3        Manchester United  ...      68.0    15.0           21.0
4          Manchester City  ...      88.0    68.0           58.0
...                    ...  ...       ...     ...            ...
18202      Crewe Alexandra  ...      45.0    40.0           48.0
18203       Trelleborgs FF  ...      42.0    22.0           15.0
18204     Cambridge United  ...      41.0    32.0           13.0
18205      Tranmere Rovers  ...      46.0    20.0           25.0
18206      Tranmere Rovers  ...      43.0    40.0           43.0

       SlidingTackle GKDiving  GKHandling  GKKicking  GKPositioning  \
0               26.0      6.0        11.0       15.0           14.0
1               23.0      7.0        11.0       15.0           14.0
2               33.0      9.0         9.0       15.0           15.0
3               13.0     90.0        85.0       87.0           88.0
4               51.0     15.0        13.0        5.0           10.0
...              ...      ...         ...        ...            ...
18202           47.0     10.0        13.0        7.0            8.0
18203           19.0     10.0         9.0        9.0            5.0
18204           11.0      6.0         5.0       10.0            6.0
18205           27.0     14.0         6.0       14.0            8.0
18206           50.0     10.0        15.0        9.0           12.0

      GKReflexes Release Clause
0            8.0        226.5M
1           11.0        127.1M
2           11.0        228.1M
3           94.0        138.6M
4           13.0        196.4M
...          ...            ...
18202        9.0          143K
18203       12.0          113K
18204       13.0          165K
18205        9.0          143K
18206        9.0          165K

[18207 rows x 89 columns]>

In [6]:
df.describe()

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18206.000000,18206.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,9103.000000,214298.338606,25.122048,66.237449,71.307299,1597.809908,1.113222,2.947299,2.361308,19.546096,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,5256.052511,29965.244204,4.670022,6.907059,6.136496,272.586016,0.394031,0.660456,0.756164,15.947765,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,0.000000,16.000000,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,4551.500000,200315.500000,21.000000,62.000000,67.000000,1457.000000,1.000000,3.000000,2.000000,8.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,9103.000000,221759.000000,25.000000,66.000000,71.000000,1635.000000,1.000000,3.000000,2.000000,17.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,13654.500000,236529.500000,28.000000,71.000000,75.000000,1787.000000,1.000000,3.000000,3.000000,26.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,18206.000000,246620.000000,45.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [7]:
total_faltantes_por_columna = df.isnull().sum()
total_faltantes_por_columna

Unnamed: 0           0
ID                   0
Name                 0
Age                  1
Photo                0
                  ...
GKHandling          48
GKKicking           48
GKPositioning       48
GKReflexes          48
Release Clause    1564
Length: 89, dtype: int64

In [8]:
df.shape

(18207, 89)

In [10]:
df.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [11]:
df.columns = df.columns.str.replace(' ','')

In [12]:
df.columns

Index(['Unnamed:0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'ClubLogo', 'Value', 'Wage', 'Special',
       'PreferredFoot', 'InternationalReputation', 'WeakFoot', 'SkillMoves',
       'WorkRate', 'BodyType', 'RealFace', 'Position', 'JerseyNumber',
       'Joined', 'LoanedFrom', 'ContractValidUntil', 'Height', 'Weight', 'LS',
       'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM',
       'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB',
       'LCB', 'CB', 'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy',
       'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
       'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
       'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
       'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'ReleaseClause'],
      dtype='object')

In [13]:
df.drop(['Unnamed:0','ID', 'Photo', 'Flag', 'ClubLogo','RealFace' ], axis=1, inplace=True)

In [14]:
df.head()

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,PreferredFoot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,ReleaseClause
0,L. Messi,31.0,Argentina,94.0,94,FC Barcelona,110.5M,565K,2202,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226.5M
1,Cristiano Ronaldo,33.0,Portugal,94.0,94,Juventus,77M,405K,2228,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127.1M
2,Neymar Jr,26.0,Brazil,92.0,93,Paris Saint-Germain,118.5M,290K,2143,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228.1M
3,De Gea,27.0,Spain,91.0,93,Manchester United,72M,260K,1471,Right,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,138.6M
4,K. De Bruyne,27.0,Belgium,91.0,92,Manchester City,102M,355K,2281,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196.4M